apiVersion: v1
kind: Namespace
metadata:
  name: torchtitan-phx
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  name: torchtitan-phx-a10-2
  namespace: torchtitan-phx
spec:
  clusterQueue: torchtitan-phx-a10-2
