apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torchtitan-oke-fss
  namespace: torchtitan-phx
spec:
  storageClassName: fss-dyn-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
